### ISSUE TITLE
Omit signature based protocol?

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#1]
Two different public key types have been discussed: signature keys and static Diffie-Hellmann keys. In the latter case signatures are replaced with MACs leading to a significant reduction of message size. For an example, see slide 11 of
https://datatracker.ietf.org/meeting/106/materials/slides-106-lake-draft-selander-lake-reqs-00.pdf
 
The current working assumption is that the AKE shall support both signature and static DH. But does LAKE really need to support signature based public keys? Restricting to static DH would significantly simplify the specification and improve performance.

Are signature based credentials necessary at all? Alternatively, the use of delegated credential is one option:
https://mailarchive.ietf.org/arch/browse/lake/?index=hCNWRcEW4ibdZjbE6Ewm7dyujbg

**Comment by gselander** [comment]
Another aspect is the ability/inability for a third party to verify that an endpoint with a certain public key has been taken part in the protocol. Does that give a reason to restrict the kind of public key used?

**Comment by seanturner** [comment]
As agreed at the interim this is to be closed.
