### ISSUE TITLE
Terminology for data chunks

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#2]
Do we need other terminology for data chunks?

Current terminology is in terms of “messages” (AKE units) and “frames”/”packets” (radio layer units). For good performance we want to minimize the number of radio layer units, the size of which are dependent on technology, regulations, configuration, etc.

The AKE is typically expected to be transported over CoAP which has its own fragmentation ("blocks"), but the AKE needs also to support other transport with analogous properties (see Section 2.1).

**Comment by mcr** [comment]
"packets" is always confusing, unless it refers to IP packets.
messages go into blocks, which are split into frames.

**Comment by gselander** [comment]
With one exception, "packets" is copying LoRaWAN terminology.

**Comment by ekr** [comment]
Assigned to @ekr to do a PR. My claim is that if there are any environments in which multiple wire-level messages can be sent during the same round trip time, we should use something that indicates that, e.g., "flight". I will take a look and either propose something or report back that we should close.
