### ISSUE TITLE
Session identifier clarification

### ISSUE THREAD

**Issue by malishav** [lake-wg/reqs#21]
Current text states:
> At the end of the AKE protocol, each end point shall have authenticated the other's credential. In particular, both endpoints must agree on a fresh session identifier, and the roles and credentials of both endpoints, both endpoints must agree on a fresh session identifier, and the roles and credentials of both endpoints.”

@ekr commented:
> What are the properties of this identifier? Is this a CK-style session identifier? I think this needs to be a lot clearer, given that you also use "connection identifier".

**Comment by ekr** [comment]
I think we ended up resolving this, so I suggest close without change.
