### ISSUE TITLE
Mutual authentication clarification

### ISSUE THREAD

**Issue by malishav** [lake-wg/reqs#22]
Current text states:
> Furthermore,the endpoints shall be able to verify that the identity of the other endpoint is an acceptable identity that it is intended to authenticate to.”

@ekr:
> Can you give me an example of something that is an AKE that doesn't otherwise have this property?

@gselander:
> A protocol that accepts the other party as long as the provided public key verifies the signature, e.g., in the “opportunisitic” setting, but in that case it is intentional.

@karthikbhargavan from the minutes of the virtual interim on 31/03/2020:
> two questions; one is about the authorization; the other one: both parties should agree on identities of both parties

**Comment by gselander** [comment]
Closed with PR #27
