### ISSUE TITLE
Resumption

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#3]
Special resumption procedure or not?

OSCORE supports a mechanism (Appendix B.2) for generating a new security context from an existing security context, based on client- and server-provided nonces, but this procedure does not provide PFS.

The AKE should support a procedure for generating a new security context with PFS from a previous authenticated key exchange between the same endpoints. This could be a dedicated session resumption procedure or a reuse of the procedures already required, such as the PSK authenticated mode of the AKE (Section 2.2) using a dedicated PSK derived after a previous AKE run.

**Comment by mcr** [comment]
I think that when it is worth (the energy) to do PFS, then it is worth doing it from first credentials, not depending upon the derived key.

**Comment by malishav** [comment]
as agreed during the interim @ekr is taking the lead on this issue

**Comment by gselander** [comment]
This issue was brought up on mailing list. Here is a proposed placeholder, details need to be discussed in the design phase: e743c873

**Comment by gselander** [comment]
Fixed by 42b8a7ef
