### ISSUE TITLE
Key separation

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#4]
What key separation properties do we need?

* Different AKE messages and OSCORE messages should all use separate keys.
* Keys used for resumption (issue #3) should be separate.
* … 

If we would use separate keys for "Application Data" (Section 2.6) in the AKE, this would add additional integrity overhead to the AKE. The planned use for "Application Data" in the AKE is to transport authorization and certificate related information. A concrete example is:

message 1: address of authorization service
message 2: voucher artifact (see draft-ietf-anima-constrained-voucher)
message 3: certificate signing request

Does this kind of data require separate keys, or can the message 2 and message 3 keys, respectively, be used for this data too?

**Comment by mcr** [comment]
I think that this example can use the same keys.
The OSCORE that results should use different keys.

**Comment by gselander** [comment]
@mcr: The use of the same keys was confirmed in the virtual interim.

**Comment by gselander** [comment]
As discussed in the interim, the term "application data" is misleading. I renamed this "auxiliary data" and added more explanation in 23b5fe8d

**Comment by gselander** [comment]
Do we need any more discussion about key separation in the requirements document, or could this be deferred to the solution?

**Comment by mcr** [comment]
I'm happy with auxiliary data.
