### ISSUE TITLE
PQC formulation

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#5]
Section 2.4 states

"PAKE and post-quantum key exchange is out of
      scope, but may be supported in a later version."

Do we need another/different statement about PQC?

**Comment by mcr** [comment]
I believe that we should split this statement up.
PAKE likely requires an additional exchange to work, so is not a drop-in replacement.
Some post-quantum key exchanges may be a drop-in, requiring, in theory, no additional exchanges. In practice might require on-the-wire frames that are big enough that some it might also require some rework.

**Comment by malishav** [comment]
as agreed during the interim, this issue is to be closed
