### ISSUE TITLE
Listing of specific attacks

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#6]
Section 2.3 lists specific attacks, such as:

"The AKE shall provide Key Compromise Impersonation (KCI) resistance"

"The AKE shall protect against reflection attacks"

Is the high level description in section 2.3 sufficient?

**Comment by mcr** [comment]
I think that we should be more precise about what aspects of KCI we might want.
My reading is that KCI depends upon the ability to do a downgrade attack on a (TLS) client first.

**Comment by malishav** [comment]
as the interim there were no objections to closing this issue.
