### ISSUE TITLE
Extensibility vs. complexity

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#7]
Section 2.7 speaks of extensibility and adds a caveat:

   "Since the main objective with this work is to create a simple yet
   secure AKE, care needs to be taken to avoid feature creep and
   extensions working against this."

Do we need a better formulation?

**Comment by mcr** [comment]
Examples of things working against this: 

- multiple ways to express the same thing, 
- things that require either end to remember what they did "last time", and do something different.

**Comment by mcr** [comment]
assign to mcr after adding him to the project.

**Comment by mcr** [comment]
Closed in favour of #11
