### ISSUE TITLE
Strength of the handshake integrity check

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#8]
What integrity do we require for the AKE? 

(See last item of 
https://mailarchive.ietf.org/arch/msg/lake/5iyqSkVEfp5rpxB2GFNAmFJUU1A)

**Comment by malishav** [comment]
as discussed during the meeting, Karthik is taking the lead on this issue

**Comment by gselander** [comment]
As discussed on the list, the detailed analysis can be deferred to the design phase. PR #14 addresses this.

**Comment by gselander** [comment]
Fixed by 19a63dd
