### ISSUE TITLE
Security requirements for the AKE compared to OSCORE

### ISSUE THREAD

**Issue by gselander** [lake-wg/reqs#9]
(Overlapping with issue #8.)

OSCORE needs AEAD, HKDF, Master Secret, Master Salt and Connection IDs. The potential relationship/independence between these and those of the AKE may be relevant to document.  See Section 2.4: "The AKE shall support different AEAD/MAC algorithms for AKE and OSCORE".
Any other such properties to list?

**Comment by malishav** [comment]
as discussed during the meeting, Karthik is taking the lead on this issue

**Comment by gselander** [comment]
PR #14 addresses this.

**Comment by gselander** [comment]
Fixed by 19a63dd
